var COUNTRYS= {
    TW: {
      TEXT: "臺灣", CITYS: [
        { value: "TW01", text: "台北市" },
        { value: "TW02", text: "基隆市" },
        { value: "TW03", text: "新北市" },
        { value: "TW04", text: "宜蘭縣" },
        { value: "TW05", text: "新竹市" },
        { value: "TW06", text: "新竹縣" },
        { value: "TW07", text: "桃園市" },
        { value: "TW08", text: "苗栗縣" },
        { value: "TW09", text: "台中市" },
        { value: "TW10", text: "彰化縣" },
        { value: "TW11", text: "南投縣" },
        { value: "TW12", text: "嘉義市" },
        { value: "TW13", text: "嘉義縣" },
        { value: "TW14", text: "雲林縣" },
        { value: "TW15", text: "台南市" },
        { value: "TW16", text: "高雄市" },
        { value: "TW17", text: "澎湖縣" },
        { value: "TW18", text: "屏東縣" },
        { value: "TW19", text: "台東縣" },
        { value: "TW20", text: "花蓮縣" },
        { value: "TW21", text: "金門縣" },
        { value: "TW22", text: "連江縣" },
        { value: "TW23", text: "南海諸島" }
      ]
    },
    CN: {
      TEXT: "中國大陸", CITYS: [
        { value: "CN01", text: "北京市" },
        { value: "CN02", text: "上海市" },
        { value: "CN03", text: "重慶市" },
        { value: "CN04", text: "天津市" },
        { value: "CN05", text: "安徽省" },
        { value: "CN06", text: "福建省" },
        { value: "CN07", text: "甘肅省" },
        { value: "CN08", text: "廣東省" },
        { value: "CN09", text: "廣西省" },
        { value: "CN10", text: "貴州省" },
        { value: "CN11", text: "海南省" },
        { value: "CN12", text: "河北省" },
        { value: "CN13", text: "黑龍江省" },
        { value: "CN14", text: "河南省" },
        { value: "CN15", text: "湖北省" },
        { value: "CN16", text: "湖南省" },
        { value: "CN17", text: "江蘇省" },
        { value: "CN18", text: "江西省" },
        { value: "CN19", text: "吉林省" },
        { value: "CN20", text: "遼寧省" },
        { value: "CN21", text: "青海省" },
        { value: "CN22", text: "陝西省" },
        { value: "CN23", text: "山東省" },
        { value: "CN24", text: "山西省" },
        { value: "CN25", text: "四川省" },
        { value: "CN26", text: "雲南省" },
        { value: "CN27", text: "浙江省" },
        { value: "CN28", text: "內蒙古自治區" },
        { value: "CN29", text: "寧夏回族自治區" },
        { value: "CN30", text: "西藏自治區" },
        { value: "CN31", text: "新疆維吾爾自治區" }
      ]
    },
    HK: { TEXT: "香港" },
    MO: { TEXT: "澳門" },
    AF: { TEXT: "AFGHANISTAN" },
    AL: { TEXT: "ALBANIA" },
    DZ: { TEXT: "ALGERIA" },
    AS: { TEXT: "AMERICAN SAMOA(U.S.A.)" },
    AD: { TEXT: "ANDORRA" },
    AO: { TEXT: "ANGOLA" },
    AR: { TEXT: "ARGENTINA" },
    AW: { TEXT: "ARUBA" },
    AU: { TEXT: "AUSTRALIA" },
    AT: { TEXT: "AUSTRIA" },
    BS: { TEXT: "BAHAMAS" },
    BH: { TEXT: "BAHRAIN" },
    BD: { TEXT: "BANGLADESH" },
    BB: { TEXT: "BARBADOS" },
    BY: { TEXT: "BELARUS" },
    BE: { TEXT: "BELGIUM" },
    BZ: { TEXT: "BELIZE" },
    BJ: { TEXT: "BENIN" },
    BM: { TEXT: "BERMUDA IS." },
    BT: { TEXT: "BHUTAN" },
    BO: { TEXT: "BOLIVIA" },
    BA: { TEXT: "BOSNIA-HERZEGOVINA REP." },
    BW: { TEXT: "BOTSWANA" },
    BR: { TEXT: "BRAZIL" },
    BN: { TEXT: "BRUNEI" },
    BG: { TEXT: "BULGARIA" },
    BF: { TEXT: "BURKINA FASO" },
    KH: { TEXT: "CAMBODIA(KAMPUCHEA)" },
    CM: { TEXT: "CAMEROON" },
    CA: { TEXT: "CANADA" },
    KY: { TEXT: "CAYMAN ISLANDS" },
    CL: { TEXT: "CHILE" },
    CO: { TEXT: "COLOMBIA" },
    CG: { TEXT: "CONGO" },
    CR: { TEXT: "COSTA RICA" },
    HR: { TEXT: "CROATIA" },
    CU: { TEXT: "CUBA" },
    CY: { TEXT: "CYPRUS" },
    CZ: { TEXT: "CZECH REP." },
    CS: { TEXT: "CZECHOSLOVAKIA" },
    DK: { TEXT: "DENMARK" },
    DM: { TEXT: "DOMINICA" },
    DO: { TEXT: "DOMINICAN REP." },
    EC: { TEXT: "ECUADOR" },
    EG: { TEXT: "EGYPT" },
    SV: { TEXT: "EL SALVADOR" },
    EE: { TEXT: "ESTONIA" },
    ET: { TEXT: "ETHIOPIA" },
    FJ: { TEXT: "FIJI" },
    FI: { TEXT: "FINLAND" },
    FR: { TEXT: "FRANCE" },
    GA: { TEXT: "GABON" },
    GM: { TEXT: "GAMBIA" },
    DE: { TEXT: "GERMANY" },
    GH: { TEXT: "GHANA" },
    GD: { TEXT: "GRENADA" },
    GP: { TEXT: "GUADELOUPE" },
    GU: { TEXT: "GUAM" },
    GT: { TEXT: "GUATEMALA" },
    GN: { TEXT: "GUINEA" },
    GY: { TEXT: "GUYANA" },
    HT: { TEXT: "HAITI" },
    GR: { TEXT: "HELLENIC(GREEK)" },
    HN: { TEXT: "HONDURAS" },
    HU: { TEXT: "HUNGARY" },
    IS: { TEXT: "ICELAND" },
    IN: { TEXT: "INDIA" },
    ID: { TEXT: "INDONESIA" },
    IR: { TEXT: "IRAN" },
    IQ: { TEXT: "IRAQ" },
    IE: { TEXT: "IRELAND" },
    IL: { TEXT: "ISRAEL" },
    IT: { TEXT: "ITALY" },
    CI: { TEXT: "IVORY COAST" },
    JM: { TEXT: "JAMAICA" },
    JP: { TEXT: "JAPAN" },
    JO: { TEXT: "JORDAN" },
    KZ: { TEXT: "KAZAKHSTAN" },
    KE: { TEXT: "KENYA" },
    KI: { TEXT: "KIRIBATI REP." },
    RK: { TEXT: "KOSOVO" },
    KW: { TEXT: "KUWAIT" },
    LA: { TEXT: "LAOS" },
    LV: { TEXT: "LATVIA" },
    LB: { TEXT: "LEBANON REP." },
    LI: { TEXT: "LIECHTENSTEIN" },
    LT: { TEXT: "LITHUANIA" },
    LU: { TEXT: "LUXEMBOURG" },
    MK: { TEXT: "MACEDONIA REP." },
    MG: { TEXT: "MADAGASCAR" },
    MW: { TEXT: "MALAWI" },
    MY: { TEXT: "MALAYSIA" },
    MV: { TEXT: "MALDIVES" },
    ML: { TEXT: "MALI REP." },
    MT: { TEXT: "MALTA" },
    MH: { TEXT: "MARSHALL ISLANDS" },
    MQ: { TEXT: "MARTINIQUE ISLAND" },
    MU: { TEXT: "MAURITIUS" },
    MX: { TEXT: "MEXICO" },
    FM: { TEXT: "MICRONESIA" },
    MD: { TEXT: "MOLDOVA REP." },
    MC: { TEXT: "MONACO" },
    MN: { TEXT: "MONGOLIA" },
    MA: { TEXT: "MOROCCO" },
    MZ: { TEXT: "MOZAMBIQUE" },
    MM: { TEXT: "MYANMAR(BURMA)" },
    NA: { TEXT: "NAMIBIA" },
    NR: { TEXT: "NAURU REP." },
    NP: { TEXT: "NEPAL" },
    NL: { TEXT: "NETHERLANDS" },
    NC: { TEXT: "NEW CALEDONIA" },
    NZ: { TEXT: "NEW ZEALAND" },
    NI: { TEXT: "NICARAGUA" },
    NE: { TEXT: "NIGER" },
    NG: { TEXT: "NIGERIA" },
    KP: { TEXT: "NORTH KOREA" },
    NO: { TEXT: "NORWAY" },
    PK: { TEXT: "PAKISTAN" },
    PW: { TEXT: "PALAU" },
    PA: { TEXT: "PANAMA" },
    PY: { TEXT: "PARAGUAY" },
    PE: { TEXT: "PERU" },
    PH: { TEXT: "PHILIPPINES" },
    PL: { TEXT: "POLAND" },
    PT: { TEXT: "PORTUGAL" },
    PR: { TEXT: "PUERTO RICO" },
    PG: { TEXT: "PUPUA NEW GUINEA" },
    QA: { TEXT: "QATAR" },
    ZA: { TEXT: "R.S.A.(SOUTH AFRICA)" },
    AM: { TEXT: "REPUBLIC OF ARMENIA" },
    RE: { TEXT: "REUNION ISLAND" },
    RO: { TEXT: "ROMANIA" },
    RU: { TEXT: "RUSSIA" },
    MP: { TEXT: "SAIPAN MARIANA IS." },
    SM: { TEXT: "SAN MARINO" },
    ST: { TEXT: "SAO TOME E PRINCIPE" },
    SA: { TEXT: "SAUDI ARABIA" },
    SN: { TEXT: "SENEGAL" },
    SC: { TEXT: "SEYCHELLES" },
    SG: { TEXT: "SINGAPORE" },
    SK: { TEXT: "SLOVAK" },
    SI: { TEXT: "SLOVENIA" },
    SB: { TEXT: "SOLOMON ISLAND" },
    KR: { TEXT: "SOUTH KOREA" },
    ES: { TEXT: "SPAIN(ESPANA)" },
    LK: { TEXT: "SRI LANKA" },
    KN: { TEXT: "ST. KITTS ST. NEVIS" },
    LC: { TEXT: "ST. LUCIA" },
    VC: { TEXT: "ST. VINCENT" },
    SD: { TEXT: "SUDAN" },
    SR: { TEXT: "SURINAM REP." },
    SZ: { TEXT: "SWAZILAMD" },
    SE: { TEXT: "SWEDEN" },
    CH: { TEXT: "SWITZERLAND" },
    SY: { TEXT: "SYRIA" },
    PF: { TEXT: "TAHITI (FRENCH POLYNESIA)" },
    TJ: { TEXT: "TAJIKISTAN" },
    TZ: { TEXT: "TANZANIA" },
    TH: { TEXT: "THAILAND" },
    TG: { TEXT: "TOGO REP." },
    TO: { TEXT: "TONGA" },
    TT: { TEXT: "TRINIDAD &amp; TOBAGO" },
    TN: { TEXT: "TUNISIA" },
    TR: { TEXT: "TURKEY" },
    TM: { TEXT: "TURKMENISTAN" },
    TC: { TEXT: "TURKS AND CAICOS IS." },
    TV: { TEXT: "TUVALU" },
    US: { TEXT: "U. S. A." },
    AE: { TEXT: "U.A.E." },
    VI: { TEXT: "U.S.A. VIRGIN ISLAND" },
    UG: { TEXT: "UGANDA" },
    UA: { TEXT: "UKRAINE" },
    GB: { TEXT: "UNITED KINGDOM" },
    UY: { TEXT: "URUGUAY" },
    UZ: { TEXT: "UZBEKISTAN" },
    VU: { TEXT: "VANUATU" },
    VA: { TEXT: "VATICAN" },
    VE: { TEXT: "VENEZUELA" },
    VN: { TEXT: "VIETNAM" },
    WS: { TEXT: "WESTERN SAMOA" },
    YE: { TEXT: "YEMEN REP." },
    YU: { TEXT: "YUGOSLAVIA" },
    ZR: { TEXT: "ZAIRE" },
    ZM: { TEXT: "ZAMBIA" },
    ZW: { TEXT: "ZIMBABWE" }
  }